[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "open3DSLAM"
authors = [{name = "open3d_slam authors", email = "jelavice@ethz.ch"}]
dynamic = ["version", "description"]
